name: 'Publish'

on:
  push:
  pull_request:

jobs:

  parse:
    name: Parse environment
    runs-on: ubuntu-latest

    outputs:
      ref: ${{steps.split.outputs._2}}

    steps:
    - uses: jungwinter/split@v1
      id: split
      with:
        msg: ${{github.ref}}
        seperator: '/' # Their documentation is incorrect... this is the expected parameter name

    - run: |
        echo "The environment will be ${{steps.split.outputs._2}}"

  publish:
    needs: parse
    name: 'Publish'
    runs-on: ubuntu-latest
    environment: ${{needs.parse.outputs.ref}}
    concurrency: ${{needs.parse.outputs.ref}}

    env:
      ARM_CLIENT_ID: ${{secrets.TF_AZ_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_AZ_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_AZ_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_AZ_TENANT_ID}}
      TF_VAR_environment: ${{needs.parse.outputs.ref}}
      TF_VAR_server_secret: ${{secrets.SERVER_SECRET}}
      TF_VAR_twilio_account_sid: ${{secrets.TWILIO_ACCOUNT_SID}}
      TF_VAR_twilio_messaging_service_id: ${{secrets.TWILIO_MESSAGING_SERVICE_ID}}
      TF_VAR_twilio_auth_token: ${{secrets.TWILIO_AUTH_TOKEN}}
      TF_VAR_twilio_connection_secret: ${{secrets.TWILIO_CONNECTION_SECRET}}
      TF_VAR_twilio_server_secret: ${{secrets.TWILIO_SERVER_SECRET}}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore src

    - name: Test
      run: dotnet test src --verbosity normal

    - name: Publish Group.Hub
      run: dotnet publish src/Group.Hub/Group.Hub.csproj -c Release -o dist/hub

    - name: Publish Group.Twilio
      run: dotnet publish src/Group.Twilio/Group.Twilio.csproj -c Release -o dist/twilio

    # Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config="key=terraform-${{needs.parse.outputs.ref}}.tfstate"

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      if: github.event_name != 'push'
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve

    # Artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts