name: 'Publish'

on:
  push:
  pull_request:

jobs:

  parse:
    name: Parse environment
    runs-on: ubuntu-latest

    outputs:
      ref: ${{steps.split.outputs._2}}

    steps:
    - uses: jungwinter/split@v1
      id: split
      with:
        msg: ${{github.ref}}
        seperator: '/' # Their documentation is incorrect... this is the expected parameter name

    - run: |
        echo "The environment will be ${{steps.split.outputs._2}}"

  publish:
    needs: parse
    name: 'Publish'
    runs-on: ubuntu-latest
    environment: ${{needs.parse.outputs.ref}}
    concurrency: ${{needs.parse.outputs.ref}}

    env:
      ARM_CLIENT_ID: ${{secrets.TF_AZ_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_AZ_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_AZ_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_AZ_TENANT_ID}}
      TF_VAR_sms_connection_string: ${{secrets.TF_VAR_SMS_CONNECTION_STRING}}
      TF_VAR_sms_service_number: ${{secrets.TF_VAR_SMS_SERVICE_NUMBER}}
      TF_VAR_environment: ${{needs.parse.outputs.ref}}
      TF_VAR_communication_service_id: ${{secrets.TF_VAR_COMMUNICATION_SERVICE_ID}}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore src

    - name: Test
      run: dotnet test src --verbosity normal

    - name: Publish
      run: dotnet publish src/Group/Group.csproj -c Release -o dist

    # Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config="key=terraform-${{needs.parse.outputs.ref}}.tfstate"

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      if: github.event_name != 'push'
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve
